

import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import Layout from "../components/Layout";

export default function AddPatientPage() {
  const navigate = useNavigate();

  useEffect(() => {
    const isLoggedIn = localStorage.getItem("loggedIn");
    if (!isLoggedIn) navigate("/");
  }, [navigate]);

  const [patient, setPatient] = useState({
    name: "",
    address: "",
    contact: "",
    date: new Date().toISOString().split("T")[0], // auto today
  });

  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");

  const handleChange = (e) => {
    setPatient({ ...patient, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setMessage("");

    if (!patient.name || !patient.contact) {
      setMessage("Name and contact are required.");
      return;
    }

    try {
      setLoading(true);

      const res = await fetch("http://localhost:5000/add_patient", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(patient),
      });

      const data = await res.json();
      if (!res.ok) {
        setMessage(data.error || "Error adding patient");
        return;
      }
      setMessage(data.msg || "Patient added successfully");

      setPatient({
        name: "",
        address: "",
        contact: "",
        date: new Date().toISOString().split("T")[0],
      });

    } catch {
      setMessage("Error adding patient");
    } finally {
      setLoading(false);
    }
  };


return (
  <Layout>
    <div className="max-w-xl mx-auto py-10">

      {/* Title */}
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-800">
          Add Patient
        </h1>
        <p className="text-sm text-gray-500">
          Enter patient details below
        </p>
      </div>

      {/* Form */}
      <form
        onSubmit={handleSubmit}
        className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 space-y-6"
      >

        {message && (
          <div className="text-sm text-blue-600 bg-blue-50 border border-blue-100 px-3 py-2 rounded-lg">
            {message}
          </div>
        )}

        {/* Name */}
        <div>
          <label className="block text-sm font-medium text-gray-600 mb-1">
            Full Name *
          </label>
          <input
            name="name"
            value={patient.name}
            onChange={handleChange}
            placeholder="Enter full name"
            className="w-full border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        {/* Contact */}
        <div>
          <label className="block text-sm font-medium text-gray-600 mb-1">
            Contact Number *
          </label>
          <input
            type="tel"
            name="contact"
            value={patient.contact}
            onChange={handleChange}
            placeholder="Enter phone number"
            className="w-full border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        {/* Address */}
        <div>
          <label className="block text-sm font-medium text-gray-600 mb-1">
            Address
          </label>
          <input
            name="address"
            value={patient.address}
            onChange={handleChange}
            placeholder="Enter address"
            className="w-full border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        {/* Date */}
        <div>
          <label className="block text-sm font-medium text-gray-600 mb-1">
            Registration Date
          </label>
          <input
            type="date"
            name="date"
            value={patient.date}
            onChange={handleChange}
            className="w-full border border-gray-300 rounded-lg px-3 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
        </div>

        {/* Info */}
        <div className="text-xs text-gray-400">
          Patient ID is automatically generated by the system.
        </div>

        {/* Submit */}
        <button
          type="submit"
          disabled={loading}
          className="w-full bg-green-600 hover:bg-green-700 text-white py-2.5 rounded-lg text-sm font-medium transition"
        >
          {loading ? "Adding Patient..." : "Add Patient"}
        </button>
      </form>
    </div>
  </Layout>
);


}

